### PR TITLE
[bugfix] MegaHaxors – ensure each instance of the ember-cli-htmlbars …

### PR DESCRIPTION
**Pull request by stefanpenner**
…add-on gets its own unique templateCompiler module

(╯°□°）╯︵ ɹǝqɯǝ

cc @rwjblue 

https://www.youtube.com/watch?v=kbW5sxyu9bU

### CODE REVIEW

**Comment by stefanpenner** [comment]
if we dropped node 0.10 we could use `vm`

**Comment by ef4** [comment]
Is there a corresponding bug against the template compiler? Because surely it is the real culprit if it can't be safely reused?

**Comment by rwjblue** [comment]
@ef4 - Yes, I am working on the issue in Ember itself (we are sharing the plugins array globally).

**Comment by rwjblue** [comment]
@ef4 https://github.com/emberjs/ember.js/pull/11376 should fix upstream (would appreciate a review).

**Pull request merged**
