### PR TITLE
Provide `cacheKey` to enable cache-busting based on runtime config

### PR DESCRIPTION
**Pull request by jobackman**
Hi,

So after #90 was merged ast-plugins could bust the cache based on directory changes, which is awesome and something addons like [ember-cli-conditional-compile](https://github.com/minichate/ember-cli-conditional-compile) has needed for a while. 

However like @rwjblue said in #90 it was made to work similarly to https://github.com/babel/broccoli-babel-transpiler/pull/89, which also includes a `cacheKey` method which augments the _cacheKeys_ based on runtime configurations rather than file-directory changes. 

It's a feature I would like to have so this is my attempt at implementing it for HTMLBars 🙏

I've been going through various PR's like #90, https://github.com/babel/broccoli-babel-transpiler/pull/89, https://github.com/ember-cli/babel-plugin-feature-flags/pull/12 and what [documentation I could find about it](https://github.com/babel/broccoli-babel-transpiler#caching) to get a grip on what it should do. 

So far I have tested it with [ember-cli-conditional-compile](https://github.com/minichate/ember-cli-conditional-compile) by registering the ast-plugin with `cacheKey` method returning its _featureFlags_ which are based on environment setup, and it's been working well so far. 

This is my first real contribution to Ember, so I might be out on deep waters, but feel free to modify or close the PR if I'm way off about this 😂

### CODE REVIEW

**Comment by reidab** [comment]
Any movement here? We're using ember-cli-conditional-compile and keep hitting issues around this.

**Comment by minichate** [comment]
Anything I can do to help with this?

**Comment by stefanpenner** [comment]
released as v1.3.0 🎉

**Comment by minichate** [comment]
Thanks!

**Comment by minichate** [comment]
@jobackman I'll work on applying this to https://github.com/minichate/ember-cli-conditional-compile right away

**Pull request merged**
